import { createRequire } from 'module'
const require = createRequire(import.meta.url)

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#a04100',
        'on-primary': '#ffffff',
        'primary-container': '#ff6b00',
        'on-primary-container': '#572000',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb693',
        'inverse-primary': '#ffb693',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7a3000',
        'secondary': '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e2e1',
        'on-secondary-container': '#656464',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474646',
        'tertiary': '#5f5e5e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9a9999',
        'on-tertiary-container': '#313131',
        'tertiary-fixed': '#e4e2e2',
        'tertiary-fixed-dim': '#c8c6c6',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#474747',
        'background': '#faf9f9',
        'on-background': '#1b1c1c',
        'surface': '#faf9f9',
        'surface-dim': '#dbdad9',
        'surface-bright': '#faf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e8',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#5a4136',
        'surface-variant': '#e3e2e2',
        'surface-tint': '#a04100',
        'inverse-surface': '#303031',
        'inverse-on-surface': '#f2f0f0',
        'outline': '#8e7164',
        'outline-variant': '#e2bfb0',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        // surface-lowest alias
        'surface-lowest': '#ffffff',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
        'section-padding-lg': '80px',
        'container-margin': '24px',
        'base': '8px',
        'element-gap': '12px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'unit': '4px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-xl': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-lg': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
        'display': ['Inter'],
        'display-mobile': ['Inter'],
      },
      fontSize: {
        'display': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-mobile': ['40px', { lineHeight: '1.1', fontWeight: '700' }],
        'headline-lg': ['52px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '900' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        'premium': '0 10px 30px -5px rgba(17, 17, 17, 0.04)',
        'float': '0px 4px 20px rgba(0, 0, 0, 0.05)',
        'soft': '0 30px 60px -12px rgba(17, 17, 17, 0.04)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
